from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.encoders import ENCODERS_BY_TYPE
from bson import ObjectId
from beanie import PydanticObjectId

ENCODERS_BY_TYPE[ObjectId] = str
ENCODERS_BY_TYPE[PydanticObjectId] = str



from app.core.config import settings
from app.core.database import init_db

# Import all routers
from app.api.auth import router as auth_router
from app.api.admin import router as admin_router



import json
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.responses import Response

def to_camel(snake_str):
    if snake_str in ('_id', 'id'):
        return 'id'
    clean_str = snake_str.lstrip('_')
    if not clean_str:
        return snake_str
    components = clean_str.split('_')
    return components[0] + ''.join(x.title() for x in components[1:])


def camelize_dict(data):
    if isinstance(data, dict):
        return {to_camel(k): camelize_dict(v) for k, v in data.items()}
    elif isinstance(data, list):
        return [camelize_dict(item) for item in data]
    return data

class CamelCaseMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request, call_next):
        response = await call_next(request)
        if response.headers.get('content-type') == 'application/json':
            body = b''
            async for chunk in response.body_iterator:
                body += chunk
            try:
                data = json.loads(body)
                camel_data = camelize_dict(data)
                camel_body = json.dumps(camel_data).encode('utf-8')
                return Response(
                    content=camel_body,
                    status_code=response.status_code,
                    media_type='application/json',
                    headers={k: v for k, v in response.headers.items() if k.lower() != 'content-length'}
                )
            except Exception as e:
                return Response(
                    content=body,
                    status_code=response.status_code,
                    media_type='application/json',
                    headers=dict(response.headers)
                )
        return response

app = FastAPI(
    title="TeamSync API",
    description="College SGP Project Management Platform",
    version="2.0.0",
    docs_url="/api/docs",
    redoc_url="/api/redoc",
)

# ─── CORS ────────────────────────────────────────────────────────────────────

app.add_middleware(CamelCaseMiddleware)
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:5174",
        "http://localhost:3000",
    ],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ─── Startup ─────────────────────────────────────────────────────────────────

@app.on_event("startup")
async def startup():
    await init_db()
    print(f"[TeamSync Server Running]: http://localhost:{settings.PORT} ({settings.APP_ENV})")
    _register_dynamic_routers()


def _register_dynamic_routers():
    """Register routers that may not exist yet (generated by subagents)."""
    import importlib, sys

    optional_routers = [
        ("app.api.groups", "router", "/api/groups"),
        ("app.api.proposals", "router", "/api/proposals"),
        ("app.api.student", "router", "/api/student"),
        ("app.api.agile", "router", "/api/agile"),
        ("app.api.supervision", "router", "/api/supervision"),
        ("app.api.faculty", "router", "/api/faculty"),
        ("app.api.collaboration", "router", "/api/collaboration"),
        ("app.api.evaluation", "router", "/api/evaluation"),
        ("app.api.platform", "router", "/api/platform"),
        ("app.api.qa", "router", "/api/qa"),
        ("app.api.reviews", "router", "/api/reviews"),
        ("app.api.releases", "router", "/api/releases"),
        ("app.api.calendar", "router", "/api/calendar"),
        ("app.api.integration", "router", "/api/integration"),
    ]
    for module_path, attr, prefix in optional_routers:
        try:
            mod = importlib.import_module(module_path)
            router = getattr(mod, attr, None)
            if router:
                app.include_router(router)
        except Exception as e:
            print(f"[Router Warning]: Could not load {module_path}: {e}")


# ─── Static Routers ───────────────────────────────────────────────────────────

app.include_router(auth_router)
app.include_router(admin_router)


# ─── Healthcheck ─────────────────────────────────────────────────────────────

@app.get("/api/health", tags=["health"])
async def health():
    return {
        "success": True,
        "message": "TeamSync API operational",
        "env": settings.APP_ENV,
    }


# ─── Global Exception Handler ────────────────────────────────────────────────

@app.exception_handler(Exception)
async def global_exception_handler(request: Request, exc: Exception):
    return JSONResponse(
        status_code=500,
        content={
            "success": False,
            "message": str(exc) if settings.APP_ENV == "development" else "Internal Server Error",
        },
    )
